---
substitutions:
  device_name: dnd-light-remote
  friendly_name: Dnd light remote
  project_version: 1.0.0
  device_description: A small remote to control the light mood for dnd

esphome:
  name: ${device_name}
  comment: ${device_description}
  project:
    name: beuluis.${device_name}
    version: ${project_version}

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret fallback_ap_password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: esphome
    password: !secret web_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: Set Day
    internal: true
    on_press:
      then:
        - homeassistant.service:
            service: input_select.select_option
            data:
              entity_id: input_select.dnd_light_mood
              option: Day
  - platform: gpio
    pin:
      number: GPIO23
      mode: INPUT_PULLUP
      inverted: true
    name: Set Night
    internal: true
    on_press:
      then:
        - homeassistant.service:
            service: input_select.select_option
            data:
              entity_id: input_select.dnd_light_mood
              option: Night
  - platform: gpio
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    name: Set Forest
    internal: true
    on_press:
      then:
        - homeassistant.service:
            service: input_select.select_option
            data:
              entity_id: input_select.dnd_light_mood
              option: Forest
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    name: Set Thunderstorm
    internal: true
    on_press:
      then:
        - homeassistant.service:
            service: input_select.select_option
            data:
              entity_id: input_select.dnd_light_mood
              option: Thunderstorm
