---
substitutions:
  device_name: door-buzzer
  friendly_name: Door buzzer
  project_version: 1.0.0
  device_description: Relay to control my door buzzer

esphome:
  name: ${device_name}
  comment: ${device_description}
  project:
    name: beuluis.${device_name}
    version: ${project_version}

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret fallback_ap_password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: esphome
    password: !secret web_password

output:
  - platform: gpio
    pin: GPIO16
    id: relay

button:
  - platform: template
    name: ${friendly_name}
    on_press:
      - output.turn_on: relay
      - delay: 3s
      - output.turn_off: relay
