---
substitutions:
  device_name: emergency-exit-sign
  friendly_name: Emergency exit sign
  project_version: 1.0.0
  device_description: A fancy emergency exit sign

esphome:
  name: ${device_name}
  comment: ${device_description}
  project:
    name: beuluis.${device_name}
    version: ${project_version}

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret fallback_ap_password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: esphome
    password: !secret web_password

light:
  # - platform: fastled_clockless
  #   chipset: NEOPIXEL
  #   pin: GPIO19
  #   num_leds: 64
  #   name: ${friendly_name}
  - platform: neopixelbus
    type: GRBW
    variant: 800KBPS
    pin: GPIO19
    num_leds: 64
    name: ${friendly_name}
