---
substitutions:
  device_name: water-tracker
  friendly_name: Water tracker
  project_version: 1.0.0
  device_description: A tracker for my daily water consumption

esphome:
  name: ${device_name}
  comment: ${device_description}
  project:
    name: beuluis.${device_name}
    version: ${project_version}

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret fallback_ap_password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: esphome
    password: !secret web_password

sensor:
  - platform: hx711
    name: "Value"
    dout_pin: GPIO16
    clk_pin: GPIO17
    update_interval: 3s
    filters:
      - calibrate_linear:
          - 551757 -> 0
          - 755263 -> 1
    unit_of_measurement: kg

switch:
  - platform: gpio
    pin: GPIO32
    name: ${friendly_name} LED
